services:
  meimaths:
    build:
      context: https://github.com/andyisdandyy/MeiMaths.git#master
      dockerfile: MeiMaths/Dockerfile
    image: meimaths:latest
    ports:
      - "4185:4185"
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - meimaths-data:/app/data
      - dataprotection-keys:/root/.aspnet/DataProtection-Keys

volumes:
  meimaths-data:
  dataprotection-keys:
